# Generated by Django 2.1.7 on 2021-01-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='context',
            new_name='content',
        ),
    ]
